target("client_tests")
    set_kind("binary")
    set_default(false)
    add_files("client/*.cpp")
    add_files("../client/src/*.cpp|main.cpp") 
    add_includedirs("../client/src")
    add_deps("protocol", "engine")
