add_requires("gtest", "nlohmann_json", "ffmpeg", "raylib")

target("client_tests")
    set_kind("binary")
    set_default(false)
    add_packages("gtest", "nlohmann_json", "ffmpeg", "raylib")
    add_defines("RTYPE_TESTING")
    add_files("client/*.cpp")
    add_files("../client/src/**.cpp|main.cpp")
    add_files("../third_party/raylib-media/src/rmedia.c")
    add_includedirs("../client/src", "../third_party/raylib-media/src")
    add_deps("protocol", "engine", "game_logic")
    add_tests("client_tests")

target("engine_tests")
    set_kind("binary")
    set_default(false)
    add_packages("gtest")
    add_files("engine/*.cpp")
    add_files("engine/util/*.cpp")
    add_files("engine/render/*.cpp")
    add_files("engine/net/*.cpp")
    add_files("engine/audio/*.cpp")
    add_links("gtest_main")
    add_deps("engine", "engine_debug", "protocol")
    add_tests("engine_tests")

target("game_logic_tests")
    set_kind("binary")
    set_default(false)
    add_files("game_logic/*.cpp")
    add_packages("gtest")
    add_deps("engine", "game_logic")
    add_files("game_logic/*.cpp")
    add_tests("game_logic_tests")

target("protocol_tests")
    set_kind("binary")
    set_default(false)
    add_files("protocol/**.cpp")
    add_packages("gtest")
    add_deps("protocol", "engine")
    add_tests("protocol_tests")
