add_requires("nlohmann_json")
add_rules("mode.debug", "mode.release")

target("game_logic")
    set_kind("static")
    add_files("src/**.cpp")
    add_includedirs("include", {public = true})
    add_headerfiles("include/game_logic/(**.h|**.hpp)")
    add_packages("nlohmann_json")
    add_deps("engine_core", "engine_ecs", "engine_math", "engine_time", "engine_util", "engine_event", "engine_scripting", "engine_input", "engine_audio")
