target("protocol")
    set_kind("static")
    set_default(false)
    add_files("src/*.cpp")
    add_includedirs("include", {public = true})
    add_headerfiles("include/protocol/**.h|**.hpp")
    add_deps("engine")

target("protocol_tests")
    set_kind("binary")
    set_default(false)
    add_files("tests/protocol_serialization_tests.cpp")
    add_deps("protocol")
