#ifndef GAME_LOGIC_GAME_INSTANCE_H_
#define GAME_LOGIC_GAME_INSTANCE_H_

#include <cstdint>
#include <memory>
#include <optional>
#include <string>
#include <string_view>
#include <unordered_map>
#include <vector>

#include "engine/ecs/registry.h"
#include "engine/event.h"
#include "engine/time/time_delta.h"
#include "game_logic/game_state.h"

namespace engine::scripting {
class ScriptEngine;
struct LuaEvent;
}  // namespace engine::scripting

namespace game_logic {

namespace systems {
class PlayerInputSystem;
class CollisionSystem;
class WeaponSystem;
class AISystem;
class MovementSystem;
class GameStateSystem;
}  // namespace systems

/**
 * @class GameInstance
 * @brief Manages a single R-Type game match
 *
 * @details
 * GameInstance orchestrates one game session (room) including:
 * - Player lifecycle (join/leave)
 * - ECS Registry ownership
 * - Component and system registration
 * - Game state tracking (level, wave, scores)
 * - Game flow control (start/update/shutdown)
 *
 * Each server can host multiple GameInstance objects representing
 * different concurrent matches.
 */
class GameInstance {
 public:
  /**
   * @brief Player-level input events handled by the game logic
   *
   * @details
   * These events are generated by the network layer or local input
   * adapter and consumed by the GameInstance input system.
   */
  enum class InputEventType : std::uint8_t {
    /// @brief Start moving left
    kMoveLeftPressed = 0,

    /// @brief Stop moving left
    kMoveLeftReleased = 1,

    /// @brief Start moving right
    kMoveRightPressed = 2,

    /// @brief Stop moving right
    kMoveRightReleased = 3,

    /// @brief Start moving up
    kMoveUpPressed = 4,

    /// @brief Stop moving up
    kMoveUpReleased = 5,

    /// @brief Start moving down
    kMoveDownPressed = 6,

    /// @brief Stop moving down
    kMoveDownReleased = 7,

    /// @brief Start Basic shoot event
    kBasicShootPressed = 8,

    /// @brief  Stop Basic shoot event
    kBasicShootReleased = 9,

    /// @brief Start Big shoot event
    kBigShootPressed = 10,

    /// @brief Stop Big shoot event
    kBigShootReleased = 11
  };

  /**
   * @brief Per-player input state used to derive velocity
   */
  struct InputState {
    bool move_left{false};
    bool move_right{false};
    bool move_up{false};
    bool move_down{false};
  };

  /**
   * @brief Event triggered when a player dies
   */
  struct PlayerDeathEvent {
    std::uint32_t player_id{0};
    std::uint8_t remaining_lives{0};
  };

  /**
   * @brief Create game instance
   * @param room_id Unique room identifier
   * @param max_players Maximum number of players (default: 4)
   */
  explicit GameInstance(std::uint32_t room_id, std::uint32_t max_players = 4);

  /**
   * @brief Destructor (calls Shutdown if not already called)
   */
  ~GameInstance();

  /// @brief Non-copyable
  GameInstance(const GameInstance &) = delete;
  GameInstance &operator=(const GameInstance &) = delete;

  /**
   * @brief Initialize and start the game
   *
   * @details
   * - Initializes game world
   * - Sets level and wave to 1
   * - Marks game as running
   *
   * Safe to call multiple times (subsequent calls ignored).
   */
  void Start();

  /**
   * @brief Update game simulation
   * @param dt Time since last frame
   *
   * @details
   * - Runs all registered ECS systems
   * - Updates player scores from components
   * - Checks win/loss conditions
   * - Updates GameState
   */
  void Update(engine::time::TimeDelta dt);

  /**
   * @brief Stop game and release resources
   *
   * @details
   * - Marks game as not running
   * - Clears all systems
   * - Removes all players
   * - Resets state
   *
   * Safe to call multiple times.
   */
  void Shutdown();

  /**
   * @brief Add player to game instance
   * @param player_id Unique player identifier
   * @param player_name Display name
   *
   * @details
   * Does nothing if:
   * - Max players reached
   * - Player already exists
   *
   * This only updates high-level GameState (no ECS entity).
   * Used internally by OnPlayerJoin().
   */
  void AddPlayer(std::uint32_t player_id, std::string_view player_name);

  /**
   * @brief Remove player from game instance
   * @param player_id Player to remove
   *
   * @details
   * Safe to call on non-existent player (no-op).
   * This only updates high-level GameState (no ECS entity).
   * Used internally by OnPlayerLeave().
   */
  void RemovePlayer(std::uint32_t player_id);

  /**
   * @brief High-level event: player joined the room
   *
   * @param player_id Unique network-level player identifier
   * @param player_name Display name
   * @return EntityId of the created ECS player entity, or std::nullopt
   *
   * @details
   * - Updates GameState and scoreboard
   * - Spawns a fully-configured player entity via PlayerBuilder
   * - Stores mapping player_id -> EntityId for later lookups
   */
  std::optional<engine::ecs::EntityId> OnPlayerJoin(
      std::uint32_t player_id, std::string_view player_name);

  /**
   * @brief High-level event: player left the room
   *
   * @param player_id Unique player identifier
   *
   * @details
   * - Kills the associated ECS entity (if any)
   * - Removes player from GameState
   * - Clears internal mappings and pending input for this player
   */
  void OnPlayerLeave(std::uint32_t player_id);

  /**
   * @brief High-level event: input received for a player
   *
   * @param player_id Unique player identifier
   * @param input_type Input event type
   *
   * @details
   * - Queues the event for this frame
   * - Events are consumed by the internal player input system
   *   registered in RegisterSystems()
   */
  void OnPlayerInput(std::uint32_t player_id, InputEventType input_type);

  /**
   * @brief Trigger a player death event
   * @param player_id Player who died
   * @param remaining_lives Lives remaining after death
   */
  void OnPlayerDeath(std::uint32_t player_id, std::uint8_t remaining_lives);

  /**
   * @brief Retrieve and clear pending death events
   */
  std::vector<PlayerDeathEvent> ExtractPlayerDeathEvents();

  /**
   * @brief Get mutable access to ECS Registry
   * @return Reference to internal registry
   *
   * @details
   * Use this to:
   * - Spawn entities
   * - Add/remove components
   * - Query component data
   */
  /**
   * @brief Get mutable access to ECS Registry
   * @return Reference to internal registry
   *
   * @details
   * Use this to:
   * - Spawn entities
   * - Add/remove components
   * - Query component data
   */
  engine::ecs::Registry &World();

  /**
   * @brief Get internal EventBus
   * @return Reference to the event bus
   *
   * @details
   * Use this to subscribe to game events (e.g., collisions) or publish
   * custom events to be handled by Lua scripts or other systems.
   */
  engine::event::EventBus &EventBus();

  /**
   * @brief Get internal ScriptEngine
   * @return Reference to the script engine
   *
   * @details
   * Access the Lua state for binding new types, running scripts manually,
   * or debugging script execution.
   */
  engine::scripting::ScriptEngine &ScriptEngine();

  /**
   * @brief Get const access to ECS Registry
   */
  const engine::ecs::Registry &World() const;

  /**
   * @brief Get current game state (read-only)
   * @return Const reference to state snapshot
   */
  const GameState &State() const;

  /**
   * @brief Get mutable game state
   * @return Reference to state (use with caution)
   */
  GameState &State();

  /**
   * @brief Check if game is currently running
   * @return true if game is running
   */
  bool IsRunning() const;

  /**
   * @brief Check if game has finished
   * @return true if game over (win or loss)
   */
  bool IsFinished() const;

  /**
   * @brief Get room identifier
   */
  std::uint32_t RoomId() const;

  /**
   * @brief Get maximum player capacity
   */
  std::uint32_t MaxPlayers() const;

  /**
   * @brief Get current number of active players
   */
  std::uint32_t ActivePlayerCount() const;

 private:
  /**
   * @brief Internal queued player input event
   */
  struct QueuedInputEvent {
    /// @brief Target player identifier
    std::uint32_t player_id{0};

    /// @brief Input event type
    InputEventType type{InputEventType::kMoveLeftPressed};
  };

  friend class systems::PlayerInputSystem;
  friend class systems::WeaponSystem;
  friend class systems::GameStateSystem;

  /**
   * @brief Register all component types with Registry
   *
   * @details
   * Registers both engine and game_logic components.
   * Called once during construction.
   */
  void RegisterComponents();

  /**
   * @brief Register all systems with Registry
   *
   * @details
   * Sets up:
   * - Player input system (variable, high priority)
   * - MovementSystem
   * - LifetimeSystem
   * Called once during construction.
   */
  void RegisterSystems();

  /**
   * @brief Initialize game world (spawn initial entities)
   *
   * @details
   * Called by Start(). Will be expanded in future tickets
   * with entity builders and wave system.
   */
  void InitializeGame();

  /**
   * @brief Sync GameState with ECS component data
   *
   * @details
   * Updates player_scores from PlayerComponent data.
   * Checks game over conditions.
   * Called each frame by Update().
   */
  void UpdateGameState();

  /// @brief Unique room identifier
  std::uint32_t room_id_;

  /// @brief Maximum allowed players
  std::uint32_t max_players_;

  /// @brief Owned ECS registry
  std::unique_ptr<engine::ecs::Registry> registry_;

  /// @brief Owned ScriptEngine
  std::unique_ptr<engine::scripting::ScriptEngine> script_engine_;

  /// @brief Owned EventBus
  engine::event::EventBus event_bus_;

  /// @brief Current game state snapshot
  GameState game_state_;

  /// @brief Player ID -> player name mapping
  std::unordered_map<std::uint32_t, std::string> player_names_;

  /// @brief Player ID -> ECS EntityId mapping
  std::unordered_map<std::uint32_t, engine::ecs::EntityId> player_entities_;

  /// @brief Per-frame queue of input events
  std::vector<QueuedInputEvent> pending_inputs_;

  /// @brief Queue of player death events
  std::vector<PlayerDeathEvent> pending_deaths_;

  /// @brief Whether Start() has been called
  bool is_started_;

  /// @brief Per-player input state
  std::unordered_map<std::uint32_t, InputState> player_input_states_;

  /// @brief Movement speed used by the input system (pixels/second)
  static constexpr float kInputMoveSpeed = 200.0f;
};

}  // namespace game_logic

#endif  // GAME_LOGIC_GAME_INSTANCE_H_
