name: Linux CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup xmake
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest
          build-cache: true

      - name: Cache apt packages
        uses: actions/cache@v3
        with:
          path: |
            /var/cache/apt
            /var/lib/apt
          key: ${{ runner.os }}-apt-${{ hashFiles('**/lockfiles') }}-${{- secrets.CACHE_VERSION || github.run_id }}
          restore-keys: |
            ${{ runner.os }}-apt-${{ hashFiles('**/lockfiles') }}-

      - name: Install clang-format
        run: |
          sudo apt-get update && sudo apt-get install -y clang-format-12
          sudo ln -s /usr/bin/clang-format-12 /usr/bin/clang-format

      - name: Set execute permissions for scripts
        run: chmod +x scripts/*.sh

      - name: Build
        run: ./scripts/build.sh

      - name: Test
        run: ./scripts/test.sh

      - name: Check format
        run: ./scripts/format-check.sh
