name: Windows CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup xmake
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest
          build-cache: true

      - name: Cache choco packages
        uses: actions/cache@v3
        with:
          path: C:\ProgramData\chocolatey\lib
          key: ${{ runner.os }}-choco-${{ hashFiles('**/lockfiles') }}-${{ secrets.CACHE_VERSION || github.run_id }}
          restore-keys: |
            ${{ runner.os }}-choco-${{ hashFiles('**/lockfiles') }}-

      - name: Install clang-format
        run: choco install llvm --version=12.0.0 -y

      - name: Build
        run: bash scripts/build.sh

      - name: Test
        run: bash scripts/test.sh

      - name: Check format
        run: bash scripts/format-check.sh
